### PR TITLE
Start adding support for React's Fragment : almost there !

### PR DESCRIPTION
**Pull request by DjebbZ**
Hi, I've started working on Rect's Fragment support for Sablono, so that you can publish a version of sablono that we can try to integrate into [rum](https://github.com/piranha/rum/pull/1).

Somes notes :
- I've arbitrarily decided to use the `:*` syntax for Fragment (i.e. `[:* [:div] [:div]]`). Feel free to choose something else.
- I've written 4 tests, only 1 fail. I've double-checked in the [online Babeljs repl](https://babeljs.io/repl/) that the syntax matches what calls to equivalent JSX would be. The failing test relies on some implementation details of Sablono (the divide between the compiler and the interpreter) that I don't really understand. Could have a look ?

I think we're pretty close to fully suppot React 16 with this. I'd love if you could continue this effort, as my understanding of Sablono is limited here.

### CODE REVIEW

**Comment by DjebbZ** [comment]
Beh, 1 fail on my machine, 2 on Travis. No idea what's happening.

**Comment by DjebbZ** [comment]
Bumping. Did you try the branch ? What's your plan regarding React's Fragment ?

**Comment by r0man** [comment]
@DjebbZ No, sorry I haven't looked into this yet. I'm fine with using ":*" for fragments. I think other react wrappers use the same. I think to move this forward, we would also need server side rednering support for this.

**Comment by nha** [comment]
```
The failing test relies on some implementation details of Sablono (the divide between the compiler and the interpreter) that I don't really understand.
```
From what I remember this is the number one problem when trying to contribute to sablono (which is great to use btw 👍  ). Maybe a small section in the README or a `CONTRIBUTING.md` explaining the idea between the divide would help new contributors?

**Comment by DjebbZ** [comment]
In the README it would be perfect.

**Comment by r0man** [comment]
Closing this, since it's merged into https://github.com/r0man/sablono/pull/181
Thanks!

**Pull request closed without merging**
