### PR TITLE
Fixed wrapped inputs with non-string values & checkboxes

### PR DESCRIPTION
**Pull request by tonsky**
First, 579f3d77271afd9edacc4fa0813f93ff42fe33a6 introduced a bug when inputs which have non-string `:value` were unable to update. Two people reported that, I hit that too, and that patch resolves that by coercing `props.value` to string before storing it into `state_value`.

Second, I just realized that `wrapped-form-element` won’t work properly for checkboxes and radio buttons, because they use `checked` instead of `value`. But they have `value` as well, it just mean different thing for them. So there’s new branch for wrapping checkboxes/radio buttons now

### CODE REVIEW

**Comment by r0man** [comment]
@tonsky The tests are failing. Also, `wrap-value-input` and `wrap-checked-input` are pretty similar. Could you please remove this duplication somehow? Either using helper fns for the individual method implementations or an additional argument to `wrap-form-element`. Something like this:

```
(defn wrap-form-element  [element attribute] ...)
(wrap-form-element "input" :value)
(wrap-form-element "checkbox" :checked)
```

I think I would prefer the second approach. What do you think?
In any case, thanks for fixing this!

**Comment by tonsky** [comment]
Yeah, I’ve seen the tests. Turned out we were still using wrapped inputs for uncontrolled components. When I fix that, it turned out that we can’t use native inputs because of value=nil in props :(

**Comment by tonsky** [comment]
Ok, I think I’ve fixed that. Tests pass, I returned single `wrap-form-element` and simplified `create-element` a little

**Comment by r0man** [comment]
@tonsky Thanks! Let me check it on one of my projects, then I'll merge it and cut a release.

**Comment by r0man** [comment]
@tonsky Ok, released as `0.7.4`. Thanks again.

**Comment by tonsky** [comment]
Hey, I noticed you’re from Berlin, right? Wanna meet tomorrow? I’ll be there https://twitter.com/nikitonsky/status/766897501534162944

**Comment by r0man** [comment]
Hey Nikita,
I'm on a surf trip through France and Spain at the moment. Next time!
Have fun in Berlin.
Roman

**Pull request merged**
