### PR TITLE
Macroexpand forms during compilation

### PR DESCRIPTION
**Pull request by aamedina**
Hello, 

I don't expect you to accept this PR as is; I mostly just want to propose this enhancement to hear your thoughts. 

Essentially my goal here is twofold: 

1. Optimize let bodies who might contain vector literals or other compile-time optimizable forms. 
2. Allow forms such as (when test then) to expand into (if test then nil) and thusly be optimizable.

### CODE REVIEW

**Comment by r0man** [comment]
Hey @aamedina,

I think this is great! I remember having tried that before, but couldn't get it working for some reason I can't remember.

Could you please add some tests, for theses scenarios, both in `compiler_test.clj` and in `core_test.clj`. That would be great. Also ,can you squash the commits into one.

Roman

**Comment by aamedina** [comment]
I added tests to sablono.compiler-test for the new optimizable forms. Could you add the corresponding tests you think are necessary to sablono.core-test? I'm not sure of the best way to define new tests there because none of the new compile-form methods should ever expand to vectors directly. The additional test cases I added pass though. I'll squash the commits now.

**Comment by r0man** [comment]
Yep, I'll take a look tomorrow ...

**Comment by r0man** [comment]
Could you also rebase on master, please.

**Comment by r0man** [comment]
Thx. Released as `0.3.4`.

**Pull request merged**
