### PR TITLE
Don't loose focus when changing controlled/uncontrolled input

### PR DESCRIPTION
**Pull request by r0man**

### CODE REVIEW

**Comment by r0man** [comment]
@roman01la Does this branch fix your problem? I added a devcard for this.
Run `lein figwheel`, then open http://localhost:3449/#!/sablono.input_test

**Comment by r0man** [comment]
Just, pushed another fix.

**Comment by roman01la** [comment]
@r0man Checked, it works as expected. Wonder why it took so much changes to `interpreter.cljc`?

**Comment by r0man** [comment]
@roman01la I think some things were not optimal in the interpreter and got messy over time. For example the call to gobject/extend in the `render` function.

**Comment by roman01la** [comment]
@r0man cool, does it need more testing? When this can be merged?

**Comment by r0man** [comment]
@roman01la  Do you have internet explorer? Could you test that fast typing doesn't loose characters in the input box?

**Comment by roman01la** [comment]
@r0man I think I have a VM with window. Will test it this evening and let you know.

**Comment by roman01la** [comment]
@r0man Checked in IE11 on Win7 image, works as expected.

**Comment by r0man** [comment]
@roman01la Thanks for testing! I'll published `0.7.8-SNAPSHOT` to Clojars.

**Comment by roman01la** [comment]
@r0man Thanks! Tested on a project, works good! 👏

**Pull request merged**
